import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv

load_dotenv()

GMAIL_SENDER       = os.getenv("GMAIL_SENDER")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD")


    
def send_report(
    to_emails  : list[str],
    subject    : str,
    body       : str,
    attachments: list[str] = []   # ← list of file paths now
) -> dict:
    if not GMAIL_SENDER or not GMAIL_APP_PASSWORD:
        return {"success": False, "error": "Gmail credentials not configured in .env"}

    try:
        msg = MIMEMultipart()
        msg["From"]    = GMAIL_SENDER
        msg["To"]      = ", ".join(to_emails)
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))

        # Attach every file in the list
        for path in attachments:
            if path and os.path.exists(path):
                with open(path, "rb") as f:
                    part = MIMEBase("application", "octet-stream")
                    part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header(
                        "Content-Disposition",
                        f"attachment; filename={os.path.basename(path)}"
                    )
                    msg.attach(part)

        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_SENDER, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_SENDER, to_emails, msg.as_string())

        return {"success": True}

    except Exception as e:
        return {"success": False, "error": str(e)}


def build_email_body(report) -> str:
    """
    Builds plain text email body from FullReport.
    Shows highlights so recipient knows what to expect in the PDF.
    """
    lines = []
    lines.append("Meeting Summary Report")
    lines.append("=" * 40)
    lines.append(f"\n{report.summary.one_line}")
    lines.append(f"Meeting Type: {report.summary.meeting_type}")

    if report.action_items:
        lines.append("\n── Action Items ──")
        for item in report.action_items:
            deadline = f" (by {item.deadline})" if item.deadline else ""
            lines.append(f"  [{item.priority}] {item.owner} → {item.task}{deadline}")

    if report.summary.decisions_made:
        lines.append("\n── Decisions ──")
        for d in report.summary.decisions_made:
            lines.append(f"  [{d.status}] {d.decision}")

    if report.risks:
        lines.append("\n── Risks & Blockers ──")
        for r in report.risks:
            lines.append(f"  [{r.severity}] {r.description}")

    if report.unresolved_questions:
        lines.append("\n── Unresolved Questions ──")
        for q in report.unresolved_questions:
            lines.append(f"  ? {q.question}")

    lines.append("\n" + "=" * 40)
    lines.append("Full report attached as PDF.")
    lines.append("Generated by MeetingIQ")

    return "\n".join(lines)
